version: '3.6'

services:
  misp-web:
    image: ghcr.io/misp/misp-docker/misp-core:latest
    container_name: misp-web
    environment:
      # MISP Configuration
      - BASE_URL=${MISP_BASEURL:-https://misp.local}
      - ADMIN_EMAIL=${MISP_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${MISP_PASSWORD:-admin}
      - ADMIN_ORG=${MISP_ORG:-ORGNAME}
      - MISP_FQDN=${MISP_FQDN:-misp.local}
      # Database Configuration
      - MYSQL_HOST=misp-db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      # Redis Configuration
      - REDIS_HOST=misp-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
      # MISP Modules Configuration
      - MISP_MODULES_FQDN=http://misp-modules
      # Worker Configuration
      - NUM_WORKERS_DEFAULT=5
      - NUM_WORKERS_PRIO=5
      - NUM_WORKERS_EMAIL=5
      - NUM_WORKERS_UPDATE=1
      - NUM_WORKERS_CACHE=5
      # SMTP Configuration
      - SMTP_FQDN=${MISP_FQDN:-misp.local}
    depends_on:
      - misp-db
      - misp-redis
      - misp-modules
      - misp-email-relay
    ports:
      - "8080:80"
    volumes:
      - ./custom/config:/var/www/MISP/app/Config
      - ./custom/scripts:/custom-scripts
    restart: unless-stopped

  misp-db:
    image: mariadb:10.5
    container_name: misp-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-misproot}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
    volumes:
      - misp-db-data:/var/lib/mysql
    restart: unless-stopped

  misp-redis:
    image: redis:alpine
    container_name: misp-redis
    command: "--save '' --requirepass '${REDIS_PASSWORD:-redispassword}'"
    restart: unless-stopped

  misp-modules:
    image: ghcr.io/misp/misp-docker/misp-modules:latest
    container_name: misp-modules
    depends_on:
      - misp-redis
    ports:
      - "6666:6666"
    restart: unless-stopped

  # Email relay service (modular)
  misp-email-relay:
    image: bytemark/smtp
    container_name: misp-email-relay
    environment:
      - RELAY_HOST=${SMTP_RELAY_HOST:-smtp.example.com}
      - RELAY_PORT=${SMTP_RELAY_PORT:-587}
      - RELAY_USERNAME=${SMTP_RELAY_USERNAME:-user}
      - RELAY_PASSWORD=${SMTP_RELAY_PASSWORD:-pass}
    # To use Office365 Graph-to-SMTP proxy, replace this service with your custom image/config
    # and update the environment variables accordingly.
    restart: unless-stopped

volumes:
  misp-db-data:

# Customization points:
# - To use a different email relay, override the misp-email-relay service.
# - Place custom configs/scripts in ./custom/config and ./custom/scripts.
# - Use 1Password integration for secure credential management.
# - Workers are now managed within the main MISP container using environment variables. 